export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Categories } from './Categories'
export { default as FeaturedServices } from './FeaturedServices'
export { default as HowItWorks } from './HowItWorks'
export { default as Faq } from './Faq'
export { default as Cta } from './Cta'
export { default as Footer } from './Footer'
